server:
  port: 8001
  
spring:
  application:
    name: provider
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.198:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}
    preferIpAddress: true
