server: 
  port: 8001
  
spring:
  application:
    name: provider
  rabbitmq: 
    host: 192.168.10.83
    username: shulong
    password: 123
    port: 5672

management: 
  security: 
    enabled: false
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.198:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${spring.application.name}
    preferIpAddress: true
env: dev1
